version: "3"

services:
    predix-edge-broker:
        image: "toke/mosquitto"
        networks:
            - predix-edge-broker_net
    grpc-server-app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
              http_proxy: $http_proxy
              https_proxy: $http_proxy
              no_proxy: $no_proxy
        image: "testgrpc"
        networks:
            - predix-edge-broker_net
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 50M
        command: ["/testGrpcServer"]
        depends_on:
            - "predix-edge-broker"
    grpc-client-app:
        image: "testgrpc"
        # environment:
        #     config: "/config/config.json"
        networks:
            - predix-edge-broker_net
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 50M
        networks:
            - predix-edge-broker_net
        depends_on:
            - "grpc-server-app"
        command: ["/testGrpcClient"]
    mqtt-app:
        image: "testgrpc"
        networks:
            - predix-edge-broker_net
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 50M
        networks:
            - predix-edge-broker_net
        depends_on:
            - "grpc-server-app"
        command: ["/mqttApp"]

networks:
  predix-edge-broker_net:
    external: true
