version: "3"

services:
    grpc-server-app:
        build:
            context: ./
            dockerfile: Dockerfile
            args:
              http_proxy: $http_proxy
              https_proxy: $http_proxy
              no_proxy: $no_proxy
        image: "testgrpc"
        # environment:
        #     config: "/config/config.json"
        depends_on:
            - "predix-edge-broker"
            - "minio1"
        deploy:
            resources:
                limits:
                    cpus: '0.20'
                    memory: 150M
        networks:
            - predix-edge-broker_net
        command: ["/testGrpcServer"]
    grpc-client-app:
        deploy:
            resources:
                limits:
                    cpus: '0.20'
                    memory: 150M
        image: "testgrpc"
        # depends_on:
        #     - "grpc-server-app"
        deploy:
            resources:
                limits:
                    cpus: '0.5'
                    memory: 50M
        networks:
            - predix-edge-broker_net
        command: ["/testGrpcClient"]
    mqtt-app:
        image: "testgrpc"
        depends_on:
            - "grpc-server-app"
        deploy:
            resources:
                limits:
                    cpus: '0.1'
                    memory: 50M
        networks:
            - predix-edge-broker_net
        command: ["/mqttApp"]
    minio1:
        image: minio/minio:RELEASE.2020-12-03T05-49-24Z
        deploy:
            resources:
                limits:
                    cpus: '0.20'
                    memory: 150M
        environment:
            MINIO_ACCESS_KEY: minio
            MINIO_SECRET_KEY: minio123
        ports:
        - '9000:9000'
        expose:
            - "9000"
        networks:
            - predix-edge-broker_net
        command: server /data
    predix-edge-broker:
        image: "toke/mosquitto"
        networks:
            - predix-edge-broker_net

networks:
  predix-edge-broker_net:
    external: true
